sudo: false

language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - go get -v pkg.re/essentialkaos/ek.v3
  - go get -v pkg.re/essentialkaos/sslscan.v1

script:
  - go build sslcli.go
