language: go

go:
  - 1.6.3
  - tip

os:
  - linux
  - osx

sudo: false

before_install:
  - go get -v pkg.re/essentialkaos/ek.v3
  - go get -v pkg.re/essentialkaos/sslscan.v1

script:
  - go build sslscan_client.go
