sudo: false

language: go

go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - os: osx

before_install:
  - make deps

script:
  - make all
