sudo: false

language: go

go:
  - 1.6.x
  - 1.7.x
  - tip

branches:
  only:
  - master
  - develop

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - go get -v pkg.re/essentialkaos/ek.v5
  - go get -v pkg.re/essentialkaos/sslscan.v3

script:
  - go build sslcli.go
