language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

os:
  - linux

services:
  - docker

branches:
  only:
  - master
  - develop

env:
  global:
    - IMAGE=essentialkaos/perfecto:centos7

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

before_install:
  - docker pull "$IMAGE"
  - wget https://kaos.sh/perfecto/perfecto-docker
  - wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v1.17.1/hadolint-Linux-x86_64
  - ./hadolint --version
  - chmod +x perfecto-docker
  - make deps

script:
  - make all
  - ./perfecto-docker common/sslcli.spec
  - ./hadolint Dockerfile
