language: go

go:
  - 1.4.3
  - 1.5.3
  - tip

os:
  - linux
  - osx

sudo: false

before_install:
  - go get -v pkg.re/essentialkaos/ek.v1
  - go get -v pkg.re/essentialkaos/ssllabs.v1

script:
  - go build ssllabs-client.go
