language: go
go:
  - 1.4.2
  - 1.5.2
  - release
  - tip

os:
  - linux
  - osx

sudo: false

before_install:
  - go get github.com/essentialkaos/ek
  - go get github.com/essentialkaos/ssllabs

script:
  - go build ssllabs-client.go
