name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 13 */15 * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SRC_DIR: src/github.com/${{ github.repository }}

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.18.x', '1.19.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Build binary
        working-directory: ${{env.SRC_DIR}}
        run: make all

  Aligo:
    name: Aligo
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.17.x'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Check Golang sources with Aligo
        uses: essentialkaos/aligo-action@v1
        with:
          path: ${{env.SRC_DIR}}
          files: ./...

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check specs with Perfecto
        uses: essentialkaos/perfecto-action@v2
        with:
          files: common/sslcli.spec

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check dockerfiles with Hadolint
        uses: essentialkaos/hadolint-action@v1
        with:
          files: Dockerfile

  DockerBuild:
    name: Docker Build Check
    runs-on: ubuntu-latest

    needs: [Hadolint, Perfecto, Aligo]

    env:
      DOCKER_FILE: Dockerfile
      IMAGE_NAME: sslcli

    steps:
      - name: Check event type
        run: |
          if [[ "${{github.event_name}}" != "pull_request" ]] ; then
            echo "::notice::Event type is not 'pull_request', all job actions will be skipped"
          fi

          # This step is a hack for needs+if issue with actions
          # More info about issue: https://github.com/actions/runner/issues/491

      - name: Checkout
        uses: actions/checkout@v3
        if: ${{ github.event_name == 'pull_request' }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        if: ${{ github.event_name == 'pull_request' && env.DOCKERHUB_USERNAME != '' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          docker build -f ${{ env.DOCKER_FILE }} -t ${{ env.IMAGE_NAME }} .

      - name: Show info about built Docker image
        uses: essentialkaos/docker-info-action@v1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          image: ${{ env.IMAGE_NAME }}
          show-labels: true
