name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 13 */15 * *'

jobs:
  Go:
    name: Go
    runs-on: ubuntu-latest

    env:
      SRC_DIR: src/github.com/${{ github.repository }}
      GO111MODULE: auto

    strategy:
      matrix:
        go: [ '1.15.x', '1.16.x' ]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Setup PATH
        run: |
          echo "GOPATH=${{ github.workspace }}" >> "$GITHUB_ENV"
          echo "GOBIN=${{ github.workspace }}/bin" >> "$GITHUB_ENV"
          echo "${{ github.workspace }}/bin" >> "$GITHUB_PATH"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ${{env.SRC_DIR}}

      - name: Download dependencies
        working-directory: ${{env.SRC_DIR}}
        run: make deps

      - name: Build binary
        working-directory: ${{env.SRC_DIR}}
        run: make all

  Perfecto:
    name: Perfecto
    runs-on: ubuntu-latest

    needs: Go

    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Perfecto docker image
        uses: docker://essentialkaos/perfecto:micro
        with:
          args: --version

      - name: Install perfecto-docker
        run: |
          wget https://kaos.sh/perfecto/perfecto-docker
          chmod +x perfecto-docker

      - name: Run Perfecto check
        env:
          IMAGE: essentialkaos/perfecto:micro
        run: ./perfecto-docker common/sslcli.spec

  Hadolint:
    name: Hadolint
    runs-on: ubuntu-latest

    needs: Go

    env:
      HADOLINT_VERSION: 2.1.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Hadolint
        run: |
          wget -O hadolint https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-Linux-x86_64
          chmod +x hadolint
      
      - name: Print Hadolint version info
        run: ./hadolint --version

      - name: Check Docker files
        run: ./hadolint Dockerfile
